language: csharp
mono: 4.2.1

sudo: false

cache:
  directories:
  - ~/.openra/Content

addons:
  apt:
    packages:
    - liblua5.1-0
    - p7zip-full

script:
 - make
 - travis_retry ./fetch-content.sh
 - make test
 - make check
 - make check-sequence-sprites

branches:
 only:
   - master

# Notify developers when build passed/failed.
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.net#openra"
    use_notice: true
    skip_join: true
