language: csharp
mono: 4.2.1

sudo: false

cache:
  directories:
  - ~/.openra/Content

addons:
  apt:
    packages:
    - liblua5.1-0
    - p7zip-full
    - nsis
    - nsis-common

script:
 - make
 - travis_retry ./fetch-content.sh
 - make test
# Crashes, see https://github.com/OpenRA/OpenRA/issues/14013
# - make check
 - make check-sequence-sprites

branches:
 only:
   - master

# Notify developers when build passed/failed.
notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.net#openra"
    use_notice: true
    skip_join: true

before_deploy:
 - mkdir build
 - cd build && ../packaging/package-all.sh ${TRAVIS_TAG} ${PWD} && cd ..
 - . mod.config

deploy:
  provider: releases
  api_key: ${GH_DEPLOY_API_KEY}
  file:
    - build/${PACKAGING_INSTALLER_NAME}-${TRAVIS_TAG}.exe
    - build/${PACKAGING_INSTALLER_NAME}-${TRAVIS_TAG}-macOS.zip
    - build/${PACKAGING_INSTALLER_NAME}-${TRAVIS_TAG}-winportable.zip
  skip_cleanup: true
  on:
    tags: true
